version: '3.8'

services:
    nginx:
        container_name: mobile_nginx_dev
        image: nginx
        volumes:
            - ./docker/nginx/:/etc/nginx/conf.d
            - ./:/app
        links:
            - php-fpm
        ports:
            - '8000:80'

    php-fpm:
        container_name: mobile_php-fpm
        build:
            context: docker
            dockerfile: php-fpm/Dockerfile
        environment:
            DB_HOST: api-postgres
            DB_USER: app
            DB_PASSWORD: secret
            DB_NAME: app
        ports:
            - 8080:8080
        volumes:
            - ./:/app
        working_dir: /app
        links:
            -   start-mobile-database

    php-cli:
        container_name: mobile_php-cli
        build:
            context: docker
            dockerfile: php-cli/Dockerfile
        environment:
            DB_HOST: api-postgres
            DB_USER: app
            DB_PASSWORD: secret
            DB_NAME: app
        volumes:
            - ./:/app
        links:
            - start-mobile-database

    start-mobile-database:
        image: mysql:8.0
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: app
            MYSQL_USER: app
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
volumes:
    persistent: